### ISSUE TITLE
How to use NW.js API?

### ISSUE THREAD

**Issue by AlesTsurko** [naviapps/create-nw-react-app#1]
Hi! Sorry for a dumb question, but how do you use NW.js API (or capture the browser's context)? I'm trying to open a popup with ```nw.Window.open()``` in the ```index.js```, but getting ``` 'nw' is not defined```.

**Comment by naviapis** [comment]
get nw object from window object.

```js
const nw = window.nw;
nw.Window.open('https://github.com');
```

or

changed to global object.
update `nw-react-scripts@^0.2.3`.

```js
nw.Window.open('https://github.com'); // direct
```

thanks.

**Comment by AlesTsurko** [comment]
Thanks!
