### ISSUE TITLE
Live Reload + DevTools

### ISSUE THREAD

**Issue by dhyegofernando** [naviapps/create-nw-react-app#12]
Hi, you've done something pretty pretty amazing. Thank you so much!!

I have just a simple issue... I couldn't get Live Reload  working... checkout it out:
![demo](https://user-images.githubusercontent.com/5576007/38251192-c07f2114-371e-11e8-9ae2-fa7e0162340e.gif)

...

How can I get DevTools working? Is there any example?

**Comment by naviapis** [comment]
Fixed live reload.

Please update nw-react-scripts library,
```bash
yarn upgrade  nw-react-scripts@1.0.9
```

Is DevTools that of nw.js?
You can open it from the right-click menu in the opened window
or open it from the menu bar window.

Thanks for the report.

**Comment by dhyegofernando** [comment]
@naviapis you're amazing.
