### ISSUE TITLE
Using styled components with boilerplate

### ISSUE THREAD

**Issue by KajBialas** [naviapps/create-nw-react-app#13]
I added `styled-components` via `yarn add styled-components`.
All is working correctly, the element is created with unique class name: `presentationstyle__ExampleContainer-imyrbt dXAAYc`, but styles from file example.style.js aren't included. File with style is imported correctly.

The specific configuration is needed in this boilerplate?

**Comment by naviapis** [comment]
Cause was found.
Please wait for updates for a while.

**Comment by naviapis** [comment]
Fixed it.
Please update nw-react-scripts library,
```
yarn upgrade nw-react-scripts@1.0.10
```
Thanks for the report.

**Comment by KajBialas** [comment]
Thanks, at this moment all is working correctly.

One case:
If I had a project build with the old version of boilerplate, run `yarn upgrade nw-react-scripts@1.0.10` it's not enough.
After building a new project with a current version of boilerplate works fine.
