### ISSUE TITLE
Public path

### ISSUE THREAD

**Issue by bcarroll22** [naviapps/create-nw-react-app#14]
Hello, great work on this package!

It looks like the public path options don't work, is this something that's expected or is there something I'm missing? I'm looking to put images in the public folder and then be able to access them by using absolute paths. Will this work using this package?

Thanks!

**Comment by naviapis** [comment]
Fixed it.

Please update `nw-react-scripts` library,

package.json

```diff
{
  "dependencies": {
-    "nw-react-scripts": "^1.0.10"
+    "nw-react-scripts": "^1.0.11"
  }
}
```

Run `yarn` or `npm update` command.

### Example

Folder structure

```
/public
  /images
    /example.png
/src
  /App.js
```

JSX

```
<img src={process.env.PUBLIC_URL + '/images/example.png'} />
  or
<img src={`${process.env.PUBLIC_URL}/images/example.png`} />
```

Thanks for the report.
