### ISSUE TITLE
Upgrade to babel core v7.0?

### ISSUE THREAD

**Issue by gitTerebi** [naviapps/create-nw-react-app#15]
Interested in having proper support for React fragments especially the <></> short syntax.

**Comment by naviapis** [comment]
This library conforms to the stable version of [Create React App](https://github.com/facebook/create-react-app).

If you want to own configuration it is possible to run the [npm run eject](https://github.com/naviapps/create-nw-react-app/blob/master/packages/nw-react-scripts/template/README.md#npm-run-eject).
