### ISSUE TITLE
How to override webpack config?

### ISSUE THREAD

**Issue by kenphil** [naviapps/create-nw-react-app#17]
I need to import 'antd' and change the theme, but how to override your webpack config?

**Comment by naviapis** [comment]
If you use custom settings you need to eject.
https://github.com/naviapps/create-nw-react-app/blob/master/packages/nw-react-scripts/template/README.md#npm-run-eject

**Comment by naviapis** [comment]
Please refer to here.
https://github.com/ant-design/create-react-app-antd
