### ISSUE TITLE
On my macbook new nw app has no text showed!

### ISSUE THREAD

**Issue by garixi** [naviapps/create-nw-react-app#20]
Starting the app with npm start produce an app with invisible text. This is happens in the inspector too.
App produced with npm build doesn't show the problem.
![schermata 2018-06-04 alle 19 27 29](https://user-images.githubusercontent.com/3479371/40932018-62b43610-682d-11e8-963f-dbda07b25f65.png)
![schermata 2018-06-04 alle 19 27 20](https://user-images.githubusercontent.com/3479371/40932019-62d44ce8-682d-11e8-84d6-d8c19e0341f0.png)

**Comment by naviapis** [comment]
Probably I think the problem of NW.js.
You can change the version of NW.js from `package.json`, so please try it.
```diff
{
    "nwBuilder": {
-       version: "latest",
+       version: "0.29.4", // https://dl.nwjs.io/
    }
}
```
