### ISSUE TITLE
nw-react-scripts: Permission denied

### ISSUE THREAD

**Issue by Benjamin-Daniel** [naviapps/create-nw-react-app#27]
I tried running npm start and it gave the error:

`> AES@0.1.0 start /home/benjamin-daniel/batcave/aes/client
> nw-react-scripts start

sh: 1: nw-react-scripts: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! AES@0.1.0 start: `nw-react-scripts start`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the AES@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by naviapis** [comment]
https://github.com/facebook/create-react-app/issues/4775
