### ISSUE TITLE
Failed to compile sqlite3 module

### ISSUE THREAD

**Issue by Kealman** [naviapps/create-nw-react-app#7]
Hi! Thank you for awesome boilerplate!
There is problem with connect [`sqlite3`](https://www.npmjs.com/package/sqlite3) lib

When I try use it, compile throws an error
```
Failed to compile.

../node_modules/sqlite3/node_modules/rc/index.js
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| var cc   = require('./lib/utils')
| var join = require('path').join

```

Version NWJS:
```
nw.js v0.27.4
Node v9.3.0
Chromium 63.0.3239.132
commit hash: f6abb93-d8d23fd-a3ef615-547fb57
```

Version create-nw-react-app  - 1.0.2

Thanks for any help

**Comment by naviapis** [comment]
It may not be possible to build sqlite3 with the latest nw.js.
* https://github.com/mapbox/node-sqlite3/issues/497
* https://github.com/mapbox/node-sqlite3/issues/891
* https://github.com/nwjs/nw.js/issues/4913

Alternatives
* [SQLite compiled to javascript](https://github.com/kripken/sql.js/)
* [Save persistent data in app
](https://github.com/nwjs/nw.js/wiki/save-persistent-data-in-app)

Thanks.

**Comment by Kealman** [comment]
Oh, it's sad :( Thanks
