### ISSUE TITLE
Can't start on ubuntu

### ISSUE THREAD

**Issue by ft115637850** [naviapps/create-nw-react-app#8]
When npm start on ubuntu, it has following error:

Error: currentPlatform selected (linux64) doesn't exist in selected platforms (win32, win64, osx64)
    at NwBuilder.runApp (/home/wwuser/my-nw-app/node_modules/nw-builder/lib/index.js:739:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by naviapis** [comment]
Please add `linux64` to `nwBuilder.platforms` of `package.json`.

The `README.md` is incomplete, but `nwBuilder` is the build setting.
https://github.com/nwjs-community/nw-builder#options

**Comment by ft115637850** [comment]
This is resolved.

**Comment by ft115637850** [comment]
By the way, do you know why the icon on the windows title bar can't show on ubuntu?

**Comment by naviapis** [comment]
It seems that favicon is displayed in the windows title bar. `index.html`
The correct setting is here.
https://github.com/nwjs/nw.js/wiki/Icons

**Comment by ft115637850** [comment]
I put the favicon.ico on ./public, add configuration in package.json as below:
`"window": {
    "icon": "./public/favicon.ico"
} `

The favicon can't show on ubuntu, but it can show on Windows10.
You can check my repo on https://github.com/ft115637850/my-nw-app.

**Comment by naviapis** [comment]
The extension is PNG / JPG only.
https://github.com/nwjs/nw.js/wiki/Icons#title-bar-icon
Please put the `logo.png` in `./public`, and set it as follows.
```"window": { "icon": "./logo.png" }```

![logo](https://user-images.githubusercontent.com/3767369/35852636-c41cb5ec-0b6e-11e8-845f-9e6e396c196e.png)

**Comment by ft115637850** [comment]
Thanks for your suggestion. But logo.png shows on windows task bar.
But I want to show it on windows title bar.
![image](https://user-images.githubusercontent.com/10191964/35904186-29ec35ba-0c1d-11e8-859f-958a0e7af19c.png)

I think this is controlled in index.html. But I am not sure whether this is an issue for NW to show it on ubuntu, because it can show on Windows.

**Comment by naviapis** [comment]
It is also not displayed in macOS.
I can not check ubuntu so I do not know any more.

Please try to ask because it is in the range of nw.js.
https://groups.google.com/forum/#!forum/nwjs-general
https://github.com/nwjs/nw.js/issues

Alternatively you can delete the frame and create it from scratch.
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Transparent%20Window/
